### ISSUE TITLE
make_bed job, internet connection error

### ISSUE THREAD

**Issue by erkinacar5** [veltenlab/MutaSeq-v2#1] opened 2022-10-24 09:35 UTC
Hello! I am trying to run the CloneTracer/nuclear-snv snakemake workflow on a cluster. On our login nodes, we have internet connection, so I managed to install all the missing libraries manually. When I start the job, of course it goes to the worker nodes of the cluster and there is no internet connection on these nodes. Due to this, I am now getting a Bioconductor version validation error. Is there any work around for this?

I am attaching both the error log and the stdout from the cluster job. Please let me know if more information is needed. Thank you in advance! :)
[lsf.o233886173.txt](https://github.com/veltenlab/CloneTracer/files/9850531/lsf.o233886173.txt)
[make_bed.log](https://github.com/veltenlab/CloneTracer/files/9850532/make_bed.log)

**Comment by sergibeneyto** [comment] 2022-11-07 16:36
Hello,

sorry for the late reply and thank you for your message. 

I modified the Snakemake workflow so that now R scripts do not require installing packages from Bioconductor/CRAN. They are pre-installed in a specific conda environment that gets created before Snakemake submits jobs to the cluster. 

Give it a try now, hopefully the problem is solved. You will have to clone the repository again as indicated in the Readme page:

`git clone https://github.com/veltenlab/CloneTracer`
`cd CloneTracer/library_processing/nuclear-snv`
`conda env create -f envs/optimized10x.yml`
`conda activate optimized10x`

Let me know if the problem persists.

**Comment by sergibeneyto** [comment] 2023-01-18 14:00
I will close this issue since it was fixed as you pointed out in issue #2

**Closed as completed by sergibeneyto** 2023-01-18 14:00 UTC
